### ISSUE TITLE
CloudFormation create_stack_set: ValidationError Parameters must have values when using empty default parameter values

### ISSUE THREAD

**Issue by ckamps** [boto/botocore#1597]
When using boto3/botocore via a Python script and when using the AWS CLI to create a CloudFormation stack set using a template that has a parameter whose default is set to `''` and a value for that parameter is not provided on the `create_stack_set()` call, botocore complains with the following error:

```
botocore.exceptions.ClientError: An error occurred (ValidationError) when calling the CreateStackSet operation: Parameters: [pTestParm1] must have values
```

# Versions
Name: boto3
Version: 1.9.14

Name: botocore
Version: 1.12.15

# Sample Template
Here's an example template:
```
AWSTemplateFormatVersion: 2010-09-09

Parameters:
  pTestParm:
    Type: String
    Default: ''

Conditions:
  cTestParmPresent: !Not [ !Equals [ !Ref pTestParm, '' ] ]

Resources:
  rTestBucket:
    Type: AWS::S3::Bucket
    Condition: cTestParmPresent
```

# AWS CLI

Here's the command used to reproduce the issue using the AWS CLI:
```
aws cloudformation create-stack-set \
                     --stack-set-name test-empty-parm \
                     --template-body file://./test-empty-parm.yml \
                     --capabilities CAPABILITY_NAMED_IAM \
                     --administration-role-arn ... \
                     --execution-role-name ... \
                     --region us-east-1 \
                     --profile ...
```

# Works With AWS Console
When the AWS console is used to create the stack set with the same test template as shown above, the stack set is created successfully.

# Works When Creating a Stack
The template is processed successfully when a CloudFormation stack is created:

```
aws cloudformation create-stack \
                     --stack-name test-empty-parm \
                     --template-body file://./test-empty-parm.yml \
                     --capabilities CAPABILITY_NAMED_IAM \
                     --region us-east-1 \
                     --profile ...
```

# Workaround
As a workaround, an arbitrary value can be used as the default value and the associated conditions can test for equivalence on that value. 

A downside of this workaround is that the dummy value used as the default value would need to conform to an AllowedPattern if it was useful to have an AllowedPattern for a given parameter. e.g. if the parameter represented an ARN, then the AllowedPattern would be the form of an ARN and the dummy value would have to be as equally complicated and long with the condition check.

For example:

```
AWSTemplateFormatVersion: 2010-09-09

Parameters:
  pTestParm:
    Type: String
    Default: 'None'

Conditions:
  cTestParmPresent: !Not [ !Equals [ !Ref pTestParm, 'None' ] ]

Resources:
  rTestBucket:
    Type: AWS::S3::Bucket
    Condition: cTestParmPresent
```
